// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/user/{user_id}/profile": {
            "post": {
                "description": "Update game user profile data, such as display name and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AdminLogin"
                ],
                "summary": "Update a game user's profile",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User profile data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.ArgsUpdateProfile"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/restapi.UserJSON"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/games/list": {
            "get": {
                "description": "Retrieves all active games and current player list. The ` + "`" + `user` + "`" + ` field of the GamePlayer object will be null.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Retrieve all currently active games",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/restapi.GameJSON"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/games/{game_id}": {
            "get": {
                "description": "Retrieves all game settings and complete player list along with their stats overview and timestamps.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Retrieve a Game by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID",
                        "name": "game_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/restapi.GameJSON"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/lobby/list": {
            "get": {
                "description": "Retrieves all active news lists, one may have the title \"policy\" which is the terms of service",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "News"
                ],
                "summary": "Retrieve News List",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/restapi.NewsJSON"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Login to a specific GameUser account using the in-game credentials",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GameUserLogin"
                ],
                "summary": "Login to a GameUser account",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/restapi.ArgsLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/restapi.UserJSON"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "description": "Logout of any currently existing session",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GameUserLogin",
                    "AdminLogin"
                ],
                "summary": "Logout of a GameUser or Admin session",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/restapi.UserJSON"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/rankings/{period}/{page}": {
            "get": {
                "description": "Retrieves top players for a particular time-period and game-mode\n- Period: all-time, weekly, archive\n- Mode: Should be a game-mode (like cap, tdm, dm, etc.) or \"all\"",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rankings"
                ],
                "summary": "Retrieve Player Rankings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Period",
                        "name": "period",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page",
                        "name": "page",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "Game Mode",
                        "name": "mode",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/restapi.RankingEntryJSON"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/profile": {
            "post": {
                "description": "Updates the profile of the currently logged in user. You can either provide just the new display name or just old and new password.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GameUserLogin"
                ],
                "summary": "Update User Profile",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.ArgsUpdateProfile"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/restapi.UserSettingsJSON"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/search/{name}/{page}": {
            "get": {
                "description": "Find users by portions of their display name",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GameUser"
                ],
                "summary": "Search User by Display Name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Page",
                        "name": "page",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/restapi.UserJSON"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/settings": {
            "post": {
                "description": "Updates the in-game settings of the currently logged in user. ALl settings must be provided.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GameUserLogin"
                ],
                "summary": "Update User Settings",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/restapi.UserSettingsJSON"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/restapi.UserSettingsJSON"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/{user_id}": {
            "get": {
                "description": "Provides the public profile of a game user (display name, last seen, rankings, etc.)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GameUser"
                ],
                "summary": "Game user's profile",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/restapi.UserJSON"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/{user_id}/games/{page}": {
            "get": {
                "description": "Retrieves a high-level summary of the games a user has played in. Summary includes points, kills, deaths along with time-stamps.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GameUser"
                ],
                "summary": "Retrieve summary of games a user has played in",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page",
                        "name": "page",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/restapi.GamePlayedJSON"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/{user_id}/settings": {
            "get": {
                "description": "Retrieves a the in-game settings for a particular user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GameUser"
                ],
                "summary": "Retrieve user's in-game settings",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/restapi.UserSettingsJSON"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/{user_id}/stats": {
            "get": {
                "description": "Retrieves all stats generated by a particular user. Stats are split-up by game mode, map, and period. So a user may not have stats generated for certain combinations yet. But if there is a All-Time stat entry, there will be a matching weekly one, even if it's empty.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GameUser"
                ],
                "summary": "Retrieve stats for a user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/restapi.PlayerStatsJSON"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/whoami": {
            "get": {
                "description": "Provides the public profile of a the currently logged in user",
                "tags": [
                    "GameUserLogin"
                ],
                "summary": "Public profile of the currently logged in game user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/restapi.UserJSON"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/restapi.ResponseJSON"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "admin.ArgsUpdateProfile": {
            "type": "object",
            "properties": {
                "displayName": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "restapi.ArgsLogin": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "restapi.GameJSON": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "current_round": {
                    "type": "integer"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lobby_id": {
                    "type": "integer"
                },
                "options": {
                    "$ref": "#/definitions/restapi.GameOptionsJSON"
                },
                "players": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/restapi.GamePlayersJSON"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "restapi.GameOptionsJSON": {
            "type": "object",
            "properties": {
                "auto_balance_count": {
                    "type": "integer"
                },
                "auto_balanced": {
                    "type": "boolean"
                },
                "blue_team": {
                    "$ref": "#/definitions/types.Team"
                },
                "cap_minutes": {
                    "type": "integer"
                },
                "cap_rounds": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "dm_minutes": {
                    "type": "integer"
                },
                "friend_fire": {
                    "type": "boolean"
                },
                "ghosts": {
                    "type": "boolean"
                },
                "has_password": {
                    "type": "boolean"
                },
                "has_voice_chat": {
                    "type": "boolean"
                },
                "idle_kick": {
                    "type": "boolean"
                },
                "idle_kick_minutes": {
                    "type": "integer"
                },
                "is_host_only": {
                    "type": "boolean"
                },
                "max_players": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                },
                "rating_restriction": {
                    "$ref": "#/definitions/types.VSRatingRestriction"
                },
                "red_team": {
                    "$ref": "#/definitions/types.Team"
                },
                "res_minutes": {
                    "type": "integer"
                },
                "res_rounds": {
                    "type": "integer"
                },
                "rules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/restapi.GameRuleJSON"
                    }
                },
                "rumble_roses": {
                    "type": "boolean"
                },
                "sne_minutes": {
                    "type": "integer"
                },
                "sne_rounds": {
                    "type": "integer"
                },
                "tdm_minutes": {
                    "type": "integer"
                },
                "tdm_rounds": {
                    "type": "integer"
                },
                "tdm_tickets": {
                    "type": "integer"
                },
                "team_kill_count": {
                    "type": "integer"
                },
                "team_kill_kick": {
                    "type": "boolean"
                },
                "unique_characters": {
                    "type": "boolean"
                },
                "weapon_restriction": {
                    "$ref": "#/definitions/types.WeaponRestrictions"
                }
            }
        },
        "restapi.GamePlayedJSON": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deaths": {
                    "type": "integer"
                },
                "deleted_at": {
                    "type": "string"
                },
                "game_has_password": {
                    "type": "boolean"
                },
                "game_host_id": {
                    "type": "integer"
                },
                "game_id": {
                    "type": "integer"
                },
                "game_name": {
                    "type": "string"
                },
                "kills": {
                    "type": "integer"
                },
                "points": {
                    "type": "integer"
                },
                "was_host": {
                    "type": "boolean"
                },
                "was_kicked": {
                    "type": "boolean"
                }
            }
        },
        "restapi.GamePlayersJSON": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deaths": {
                    "type": "integer"
                },
                "deleted_at": {
                    "type": "string"
                },
                "kills": {
                    "type": "integer"
                },
                "ping": {
                    "type": "integer"
                },
                "score": {
                    "type": "integer"
                },
                "team": {
                    "$ref": "#/definitions/types.Team"
                },
                "team_string": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/restapi.UserJSON"
                },
                "user_id": {
                    "type": "integer"
                },
                "was_kicked": {
                    "type": "boolean"
                }
            }
        },
        "restapi.GameRuleJSON": {
            "type": "object",
            "properties": {
                "map": {
                    "$ref": "#/definitions/types.GameMap"
                },
                "map_string": {
                    "type": "string"
                },
                "mode": {
                    "$ref": "#/definitions/types.GameMode"
                },
                "mode_string": {
                    "type": "string"
                }
            }
        },
        "restapi.LobbyJSON": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "players": {
                    "type": "integer"
                }
            }
        },
        "restapi.NewsJSON": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "restapi.PlayerStatsJSON": {
            "type": "object",
            "properties": {
                "cqc_attacks": {
                    "type": "integer"
                },
                "cqc_attacks_received": {
                    "type": "integer"
                },
                "death_streak": {
                    "type": "integer"
                },
                "deaths": {
                    "type": "integer"
                },
                "head_shots": {
                    "type": "integer"
                },
                "head_shots_received": {
                    "type": "integer"
                },
                "infrared_goggle_uses": {
                    "$ref": "#/definitions/time.Duration"
                },
                "kerotans_for_win": {
                    "description": "KerotansForWin is the number of Gakos rescued when Mode is rescue",
                    "type": "integer"
                },
                "kerotans_placed": {
                    "description": "KerotansPlaced is the number of goals as snake when Mode is sneaking",
                    "type": "integer"
                },
                "kill_streak": {
                    "type": "integer"
                },
                "kills": {
                    "type": "integer"
                },
                "kills_with_knife": {
                    "type": "integer"
                },
                "kills_with_scorpion": {
                    "type": "integer"
                },
                "map": {
                    "$ref": "#/definitions/types.GameMap"
                },
                "map_string": {
                    "type": "string"
                },
                "mode": {
                    "$ref": "#/definitions/types.GameMode"
                },
                "mode_string": {
                    "type": "string"
                },
                "period": {
                    "$ref": "#/definitions/types.PlayerStatsPeriod"
                },
                "period_string": {
                    "type": "string"
                },
                "play_time": {
                    "$ref": "#/definitions/time.Duration"
                },
                "points": {
                    "type": "integer"
                },
                "radio_uses": {
                    "type": "integer"
                },
                "rank": {
                    "description": "Rank will be the rank in the mode for the period. Though stats are broken down by map also, the rank value will only consider mode.",
                    "type": "integer"
                },
                "rolls": {
                    "type": "integer"
                },
                "rounds_no_death": {
                    "type": "integer"
                },
                "rounds_played": {
                    "type": "integer"
                },
                "self_stuns": {
                    "type": "integer"
                },
                "snake_frags": {
                    "type": "integer"
                },
                "stuns": {
                    "type": "integer"
                },
                "stuns_received": {
                    "type": "integer"
                },
                "suicides": {
                    "type": "integer"
                },
                "team_kills": {
                    "type": "integer"
                },
                "team_stuns": {
                    "type": "integer"
                },
                "team_wins": {
                    "type": "integer"
                },
                "text_chat_uses": {
                    "type": "integer"
                },
                "times_eaten": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "restapi.RankingEntryJSON": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "points": {
                    "type": "integer"
                },
                "rank": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "restapi.ResponseJSON": {
            "type": "object",
            "properties": {
                "data": {},
                "success": {
                    "type": "boolean"
                }
            }
        },
        "restapi.UserJSON": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "emblem_text": {
                    "type": "string"
                },
                "has_emblem": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "overall_rank": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "weekly_rank": {
                    "type": "integer"
                }
            }
        },
        "restapi.UserSettingsJSON": {
            "type": "object",
            "properties": {
                "equipment_switch_style": {
                    "type": "string"
                },
                "fkeys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "fpv_invert_horizontal": {
                    "type": "boolean"
                },
                "fpv_invert_vertical": {
                    "type": "boolean"
                },
                "fpv_rotation_speed": {
                    "type": "integer"
                },
                "fpv_switch_orientation": {
                    "type": "string"
                },
                "show_name_tags": {
                    "type": "boolean"
                },
                "switch_speed": {
                    "type": "integer"
                },
                "tpv_chase_camera": {
                    "type": "boolean"
                },
                "tpv_invert_horizontal": {
                    "type": "boolean"
                },
                "tpv_invert_vertical": {
                    "type": "boolean"
                },
                "tpv_rotation_speed": {
                    "type": "integer"
                },
                "weapon_switch_style": {
                    "type": "string"
                }
            }
        },
        "time.Duration": {
            "type": "integer",
            "enum": [
                -9223372036854775808,
                9223372036854775807,
                1,
                1000,
                1000000,
                1000000000,
                60000000000,
                3600000000000
            ],
            "x-enum-varnames": [
                "minDuration",
                "maxDuration",
                "Nanosecond",
                "Microsecond",
                "Millisecond",
                "Second",
                "Minute",
                "Hour"
            ]
        },
        "types.GameMap": {
            "type": "integer",
            "enum": [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12
            ],
            "x-enum-varnames": [
                "MapLostForest",
                "MapGhostFactory",
                "MapCityUnderSiege",
                "MapKillhouseA",
                "MapKillhouseB",
                "MapKillhouseC",
                "MapSvyatogornyjEast",
                "MapMountainTop",
                "MapGraninyGorkiLab",
                "MapPillboxPurgatory",
                "MapHighIce",
                "MapBrownTown"
            ]
        },
        "types.GameMode": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4,
                5
            ],
            "x-enum-comments": {
                "ModeOverall": "Only used by the Rankings request"
            },
            "x-enum-varnames": [
                "ModeDeathmatch",
                "ModeTeamDeathmatch",
                "ModeRescue",
                "ModeCapture",
                "ModeSneaking",
                "ModeOverall"
            ]
        },
        "types.PlayerStatsPeriod": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-varnames": [
                "PeriodAllTime",
                "PeriodWeekly",
                "PeriodArchive"
            ]
        },
        "types.Team": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-varnames": [
                "TeamGRU",
                "TeamKGB",
                "TeamOcelot"
            ]
        },
        "types.VSRatingRestriction": {
            "type": "integer",
            "enum": [
                0,
                2,
                1
            ],
            "x-enum-varnames": [
                "VSRatingRestrictionNone",
                "VSRatingRestrictionBelow",
                "VSRatingRestrictionAbove"
            ]
        },
        "types.WeaponRestrictions": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                7
            ],
            "x-enum-varnames": [
                "WeaponRestrictionsNone",
                "WeaponRestrictionsNoPrimary",
                "WeaponRestrictionsNoSecondary",
                "WeaponRestrictionsNoSupport",
                "WeaponRestrictionsPrimaryOnly",
                "WeaponRestrictionsSecondaryOnly",
                "WeaponRestrictionsSupportOnly",
                "WeaponRestrictionsKnifeOnly"
            ]
        },
        "user.ArgsUpdateProfile": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "old_password": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "localhost:8088",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Metal Gear Online 1 API",
	Description:      "API for accessing MGO1 game and user data",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
